[plugins."github@openai-curated"]
enabled = false

[plugins."computer-use@openai-bundled"]
enabled = false

[plugins."build-ios-apps@openai-curated"]
enabled = false

[plugins."build-macos-apps@openai-curated"]
enabled = false
