[env.production]
name = "lanzhijiang"
main = "src/worker/index.ts"
compatibility_date = "2026-03-01"
routes = [
  { pattern = "lanzhijiang.dev/api/*", zone_name = "lanzhijiang.dev" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "xiaoland-site"
database_id = "62f4f604-e106-4c2d-aed5-f512066529b6"
migrations_dir = "drizzle"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "xiaoland-site-preview"
database_id = "279b5c63-5036-410d-9614-3b63259c425c"
migrations_dir = "drizzle"
